# Generated by Django 3.1.7 on 2021-03-15 03:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipment_name', models.CharField(max_length=20)),
                ('Equipment_ID', models.IntegerField(unique=True)),
                ('Serial_no', models.IntegerField()),
                ('Category', models.CharField(max_length=20)),
                ('Model', models.CharField(max_length=20)),
                ('Make', models.CharField(max_length=20)),
                ('Buy_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Rent_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Invoice_no', models.IntegerField(unique=True)),
                ('Rental_Period', models.IntegerField()),
                ('Invoice_Amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_no', models.IntegerField(unique=True)),
                ('PO_no', models.IntegerField()),
                ('Job_name', models.CharField(max_length=20)),
                ('Phase', models.CharField(max_length=20)),
                ('Job_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendor_no', models.IntegerField(unique=True)),
                ('Vendor_name', models.CharField(max_length=20)),
                ('Salesman', models.CharField(max_length=20)),
                ('Phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rental_ID', models.IntegerField()),
                ('Buy_or_Rent', models.CharField(max_length=10)),
                ('Date_Received', models.DateTimeField(default=django.utils.timezone.now)),
                ('Return_Status', models.BooleanField(default=False)),
                ('Date_Returned', models.DateTimeField(blank=True, null=True)),
                ('Expected_Duration', models.IntegerField()),
                ('Invoice_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.invoice', to_field='Invoice_no')),
                ('equipment_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.equipment', to_field='Equipment_ID')),
                ('job_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.job', to_field='Job_no')),
                ('vendor_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.vendor', to_field='Vendor_no')),
            ],
            options={
                'verbose_name': 'Rentals',
                'verbose_name_plural': 'Rentals',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='job_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.job', to_field='Job_no'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='vendor_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.vendor', to_field='Vendor_no'),
        ),
    ]
