# Generated by Django 3.1.7 on 2021-03-16 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20210316_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentals',
            name='job_no',
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='vendor_no',
        ),
        migrations.AddField(
            model_name='rentals',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.job', to_field='Job_no'),
        ),
        migrations.AddField(
            model_name='rentals',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.vendor', to_field='Vendor_no'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Equipment_ID',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Invoice_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Vendor_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
