# Generated by Django 3.1.7 on 2021-03-16 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_auto_20210316_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentals',
            name='job',
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='vendor',
        ),
        migrations.AddField(
            model_name='rentals',
            name='job_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.job', to_field='Job_no'),
        ),
        migrations.AddField(
            model_name='rentals',
            name='vendor_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.vendor', to_field='Vendor_no'),
        ),
    ]
