# Generated by Django 3.1.7 on 2021-03-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20210316_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='vendor_no',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='job_no',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='rentals',
            old_name='job_no',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='rentals',
            old_name='vendor_no',
            new_name='vendor',
        ),
    ]
